### ISSUE TITLE
Cannot find module 'tfrecords' or its corresponding type declarations.

### ISSUE THREAD

**Issue by mkabatek** [JacopoMangiavacchi/TFRecords#2]
Hello,

I'm trying to use this package in an application to generate tfrecords for training. However when I add this to my project

```yarn add tfrecords``` 

It appears to be installed correct however when I try and run my application I see

```Cannot find module 'tfrecords' or its corresponding type declarations.```

I'm unable to import the module, any idea how to fix this issue?

**Comment by chebum** [comment]
I made a pull request fixing this issue:
https://github.com/JacopoMangiavacchi/TFRecords/pull/3
